apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: default-kubecf-tests-sits-cluster-binding
  name: default-tests-sits-cluster-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: default-tests-sits-cluster-role
subjects:
- kind: ServiceAccount
  name: tests-sits
  namespace: default
